require:
  - rubocop-performance
  - rubocop-rspec

# METRICS
MethodLength:
  CountComments: false
  Max: 15
  Exclude:
    - 'spec/**/*'
Metrics/LineLength:
  Enabled: false
Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'spec/**/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# LAYOUT
Layout/DotPosition:
  EnforcedStyle: leading
  Enabled: true
Layout/ExtraSpacing:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

# STYLE
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false

# NAMING
Naming/FileName:
  Exclude:
    - 'demo/**/*'

# RSPEC
RSpec/ContextWording:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Max: 5
RSpec/VerifiedDoubles:
  Enabled: false
